#!/bin/bash
set -e

HERE="$(dirname "$(readlink -f "$0")")"
export PATH="${HERE}/usr/bin:${PATH}"
export PYTHONPATH="${HERE}/usr/lib/python3/dist-packages:${PYTHONPATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${HERE}/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"

# Ensure compression tools are in PATH
export PATH="/usr/bin:${PATH}"

exec "${HERE}/usr/bin/curtail" "$@"